apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world36-backend.fullname" . }}
  labels:
    {{- include "hello-world36-backend.labels" . | nindent 4 }}
    {{ if .Values.service.labels}}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world36-backend.selectorLabels" . | nindent 4 }}
