containers:
  - name: {{ .Chart.Name }}
    dev:
      gitUrl: {{ .Values.nocalhost.gitUrl }}
      image: ghcr.io/nocalhost/dev-container/node:latest
      shell: bash
      workDir: /home/nocalhost-dev
      command:
        run: [ "npm install && npm run dev -- -p 80" ]
        debug: [ "npm install && npm run dev -- -p 80" ]
      debug:
        language: "node"
        remoteDebugPort: 9009
      hotReload: false
      sync:
        type: send
        filePattern:
          - ./
        ignoreFilePattern:
          - ".git"
          - ".idea"
          - ".github"
          - "node_modules"
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "0.2"
          memory: 256Mi
