hello-world36-backend:
  nocalhost:
    gitUrl: "https://github.com/deer-org/forkmain23-backend"
    # default prefix is "{{ Release.Namespace }}."

    # example:

    # ingressURLPrefix: "dev."
    annotations:
      path: conf/nocalhost.yaml
  # deployment env

  env:
    - name: HOST
      value: h8r.dev
    - name: PASSWORD
      value: my_secret
    - name: forkmain23_MY_DB_USERNAME
      value: admin
    - name: forkmain23_MY_DB_PASSWORD
      value: password
    - name: forkmain23_MY_DB_URL
      value: my_db.default.svc
  #   - name: "foo"

  #     value: "bar"
  replicaCount: 1
  image:
    repository: ghcr.io/deer-org/forkmain23-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.

    tag: "main"
  imagePullSecrets:
    - name: forkmain23
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account

    annotations: {}
    # The name of the service account to use.

    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
    runAsUser: 0
  # capabilities:

  #   drop:

  #   - ALL

  # readOnlyRootFilesystem: true

  # runAsNonRoot: true

  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
    labels: {}
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/ingress.class: nginx

    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: forkmain23.h8r.site
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
  #    hosts:

  #      - chart-example.local
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious

  # choice for the user. This also increases chances charts run on environments with little

  # resources, such as Minikube. If you do want to specify resources, uncomment the following

  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.

  # limits:

  #   cpu: 100m

  #   memory: 128Mi

  # requests:

  #   cpu: 100m

  #   memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
hello-world36-frontend:
  nocalhost:
    gitUrl: "https://github.com/deer-org/forkmain23-frontend"
    # default prefix is "{{ Release.Namespace }}."

    # example:

    # ingressURLPrefix: "dev."
    annotations:
      path: conf/nocalhost.yaml
  # deployment env

  env:
    - name: HOST
      value: h8r.dev
    - name: PASSWORD
      value: my_secret
    - name: KEY
      value: VALUE
  #   - name: "foo"

  #     value: "bar"
  replicaCount: 1
  image:
    repository: ghcr.io/deer-org/forkmain23-frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.

    tag: "5eb2f5a"
  imagePullSecrets:
    - name: forkmain23
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account

    annotations: {}
    # The name of the service account to use.

    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
    runAsUser: 0
  # capabilities:

  #   drop:

  #   - ALL

  # readOnlyRootFilesystem: true

  # runAsNonRoot: true

  # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    # kubernetes.io/ingress.class: nginx

    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: bug-fix-hello-world36.h8r.site
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
  #    hosts:

  #      - chart-example.local
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious

  # choice for the user. This also increases chances charts run on environments with little

  # resources, such as Minikube. If you do want to specify resources, uncomment the following

  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.

  # limits:

  #   cpu: 100m

  #   memory: 128Mi

  # requests:

  #   cpu: 100m

  #   memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
